### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by prashanthsidd** [prashanthsidd/BD2017#3]

**Comment by prashanthsidd** [comment]
The assignment is carried out on a single host.

**Comment by HorizonNet** [comment]
Below is a short review.

**Tasks**

- [ ] System Configuration Checks
- [ ] MySQL installation
- [ ] CM/CDH installation
- [ ] Using the CM API
- [x] Upgrade Cloudera Manager
- [x] Using a local parcel repository

Open points:

I'm not an Ubuntu expert, so some of the comments could be RHEL-specific.

* System Configuration Checks
  * The command for the mount attributes of all volumes is wrong. Hint: You have to check a specific file on disk for that.
  * The command for showing the reserved spaced is wrong. There's no need to loop through the devices.
  * The command for disabling transparent hugepage support should not be sufficient. If you run the host inspector in Cloudera Manager it should still warn you about this point.
  * The command for displaying the network interface configuration is wrong. Hint: You have to check a specific file on disk for that.
  * Regarding `nscd` and `ntpd`: You should only show the commands that ensure that these services are running.
* MySQL installation
  * The databases for the different services are missing.
* CM/CDH installation
  * Instead of MySQL you have a PostgreSQL backing your CM installation. This seems not to fit to the rest of your submissions, where MySQL seems to back the different services.
  * The command for checking the current state of the Hive service is missing.

General feedback:

Regarding Ubuntu, that's fine for the class, but you should get used to RHEL. It's the standard operating system I see in every cluster installation.
